maven-build:
  image: maven:3-jdk-8
#  stage: build
#  script: "mvn clean deploy -DskipTests -DrepositoryId=phonepe-snapshots"
#  artifacts:
#    paths:
#      - target/*.jar

  variables:
    MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

  cache:
    paths:
      - .m2/repository/
      - target/

  build:
    stage: build
    script:
      - mvn $MAVEN_CLI_OPTS compile

  test:
    stage: test
    script:
      - mvn $MAVEN_CLI_OPTS test

  deploy:
    stage: deploy
    script:
      - mvn $MAVEN_CLI_OPTS deploy
    only:
      - master
